apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: urlshortener
type: Opaque
# Database credentials encoded in base64
data:
  POSTGRES_USER: ZGV2dXNlcg==
  POSTGRES_PASSWORD: ZGV2cGFzc3dvcmQ=
  POSTGRES_DB: aG9zdGRi