apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-serviceaccount
  namespace: urlshortener
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-sidecar-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-sidecar-role-binding
subjects:
- kind: ServiceAccount
  name: grafana-serviceaccount
  namespace: urlshortener
roleRef:
  kind: ClusterRole
  name: grafana-sidecar-role
  apiGroup: rbac.authorization.k8s.io