apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: urlshortener
  labels:
    app: grafana
data:
  # The configuration file that Grafana reads
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        # The URL points to the Prometheus Service inside the cluster
        url: http://prometheus-service.urlshortener:9090
        isDefault: true
        version: 1
        editable: true
        # Timeout for query requests to the data source.
        jsonData:
          timeInterval: "5s"