# Prometheus Data Source Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: urlshortener
  labels:
    grafana_datasource: "1" 
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus_ds
      type: prometheus
      uid: prometheus_ds
      access: proxy
      url: http://prometheus-service.urlshortener.svc.cluster.local:9090
      isDefault: true
      jsonData:
        timeInterval: "15s"

---

# Dashboards Provider Config 
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provider
  namespace: urlshortener
data:
  provider.yaml: |-
    apiVersion: 1
    providers:
    - name: 'Sidecar Provider'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards

