apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: urlshortener
  labels:
    app: grafana
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana-serviceaccount
      securityContext:
        fsGroup: 472 
      containers:
      - name: grafana
        image: grafana/grafana:10.2.3 
        ports:
        - containerPort: 3000
        env:
          - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
            value: "/var/lib/grafana/dashboards/app-metrics.json" 
        volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var/lib/grafana

        - name: sc-dashboard-volume
          mountPath: /var/lib/grafana/dashboards

        - name: dashboard-provider-volume
          mountPath: /etc/grafana/provisioning/dashboards/provider.yaml
          subPath: provider.yaml
        
        - name: sc-datasource-volume 
          mountPath: /etc/grafana/provisioning/datasources/prometheus.yaml
          subPath: prometheus.yaml

        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
      
      - name: grafana-sc-dashboard
        image: kiwigrid/k8s-sidecar:latest
        env:
          - name: LABEL
            value: "grafana_dashboard"
          - name: FOLDER
            value: "/var/lib/grafana/dashboards"
          - name: RESOURCE
            value: "configmap"
          - name: NAMESPACE
            value: "urlshortener"
          - name: HTTP_PORT
            value: "8081"
        volumeMounts:
        - name: sc-dashboard-volume
          mountPath: /var/lib/grafana/dashboards
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: grafana-persistent-storage
        emptyDir: {} 
      - name: sc-dashboard-volume
        emptyDir: {}
      - name: dashboard-provider-volume
        configMap:
          name: grafana-dashboards-provider
      - name: sc-datasource-volume
        configMap:
          name: grafana-datasource-config