apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: urlshortener
  labels:
    app: multi-component-app
type: Opaque
data:
  DB_USERNAME: ZGV2dXNlcgo=
  DB_PASSWORD: ZGV2cGFzc3dvcmQK
  DB_NAME: XJsZGIK