apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: urlshortener
  labels:
    app: multi-component-app
data:
  FRONTEND_API_URL: "http://backend-service:5000/api/"
  REACT_APP_ENV: production